apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "IBMLicensingHub",
          "metadata": {
            "name": "example-ibmlicensinghub"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-licensing-hub-operator.v1.2.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: IBMLicensingHub is the Schema for the ibmlicensinghubs API
      kind: IBMLicensingHub
      name: ibmlicensinghubs.operator.ibm.com
      specDescriptors:
      - description: Accept is an opt-in license acceptance required to deploy resources
        displayName: License Acceptance
        path: license.accept
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      version: v1alpha1
  displayName: Ibm Licensing Hub Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - name: ibm-licensing-hub-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-licensing-hub-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-licensing-hub-operator
            spec:
              containers:
              - command:
                - ibm-licensing-hub-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-licensing-hub-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: ibm-licensing-hub-operator
                resources: {}
              serviceAccountName: ibm-licensing-hub-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - ibm-licensing-hub-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - operator.ibm.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ibm-licensing-hub-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ""
  maintainers:
  - {}
  maturity: alpha
  provider: {}
  version: 1.2.0
